apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "mongo-pvc.fullname" . }}
spec:
  storageClassName: yc-network-hdd
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  # volumeName: {{ template "mongo-pv.fullname" . }}
