---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "network.policy.fullname" . }}
  labels:
    app: reddit
spec:
  podSelector:
    matchLabels:
      app: reddit
      component: mongo
      release: {{ .Release.Name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: reddit
          component: comment
          release: {{ .Release.Name }}
    - podSelector:
        matchLabels:
          app: reddit
          component: post
          release: {{ .Release.Name }}
