version: '3'
services:
  zipkin:
    image: openzipkin/zipkin:${ZIPKIN_VERSION}
    networks:
      - front_net
      - back_net
    ports:
      - 9411:${ZIPKIN_PORT}
  fluentd:
    image: ${USERNAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:${STACK_VERSION}
    environment:
      - node.name=elasticsearch
      - ELASTIC_CLUSTER=false
      - CLUSTER_NODE_MASTER=true
      - CLUSTER_MASTER_NODE_NAME=elasticsearch
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    expose:
      - ${ES_PORT}
    ports:
      - ${ES_PORT}:${ES_PORT}

  kibana:
    image: kibana:${STACK_VERSION}
    ports:
      - ${KIBANA_PORT}:5601

networks:
  back_net:
  front_net:
