version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_REV}    # 3.6
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    # build: ./ui
    image: ${USERNAME}/ui:${UI_REV}
    ports:
      - ${APP_PORT}:${APP_PORT}/tcp     # 9292
    networks:
      - front_net
  post:
    # build: ./post-py
    image: ${USERNAME}/post:${POST_REV}
    networks:
      - back_net
      - front_net
  comment:
    # build: ./comment
    image: ${USERNAME}/comment:${COMMENT_REV}
    networks:
      - back_net
      - front_net
  prometheus:
    image: ${USERNAME}/prometheus
    networks:
      - back_net
      - front_net
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command: # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день

  node-exporter:
    image: prom/node-exporter:v0.15.2
    networks:
      - back_net
      - front_net
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'

volumes:
  post_db:
  prometheus_data:

networks:
  front_net:
  back_net:
