version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_REV}    # 3.6
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI_REV}
    ports:
      - 9292:${APP_PORT}/tcp     # 9292
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${USERNAME}/post:${POST_REV}
    networks:
      - back_net
      - front_net
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_REV}
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  front_net:
  back_net:
